[package]
name = "qodex-desktop"
version = "0.2.0-beta.2"
description = "KerniQ Desktop Shell"
authors = ["KerniQ"]
edition = "2021"

[lib]
name = "qodex_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
sha2 = "0.10"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
