[package]
name = "qodex-desktop"
version = "0.6.0"
description = "KerniQ Desktop Shell"
authors = ["KerniQ"]
edition = "2021"

[lib]
name = "qodex_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
sha2 = "0.10"
flate2 = "1"
fs2 = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
tar = "0.4"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
