import { describe, it, expect } from "vitest";
import { Coordinator, TaskPlanner, SpecialistFactory } from "../src/index.js";

describe("Diff Engine Integration (Planner)", () => {
  it("patch proposals are not auto-generated by specialists", () => {
    const c = new Coordinator();
    c.initialize();
    const plan = c.planner.createPlan("Refactor");
    // Specialists produce reports, not patches
    expect(plan.subTasks.some((s) => s.agentRole === "refactor")).toBe(true);
  });

  it("specialists cannot write files directly", () => {
    const f = new SpecialistFactory();
    const agents = f.createDefaultSet();
    for (const a of agents) {
      expect((a as any).writeFile).toBeUndefined();
    }
  });
});

describe("Git Runtime Integration", () => {
  it("checkpoints should be created before applying patches", () => {
    const c = new Coordinator();
    c.initialize();
    // Coordinator does not auto-create checkpoints
    expect((c as any).checkpoint).toBeUndefined();
  });
});

describe("MCP Runtime Integration", () => {
  it("specialists may request MCP tools but permissions still required", () => {
    const c = new Coordinator();
    c.initialize();
    // Specialists don't bypass MCP permissions
    expect((c as any).mcp).toBeUndefined();
  });
});
